### ISSUE TITLE
Error in console on home page

### ISSUE THREAD

**Issue by xlanex6** [double-slash-podcast/website#34]
On home page 

![CleanShot 2022-10-26 at 17 29 13](https://user-images.githubusercontent.com/13418668/198069466-c1b84158-fd05-443e-9576-41ce9a342bd0.png)

`TypeError: t.pause is not a function`

**Comment by ipatate** [comment]
error is more explicit in dev mode. It's always the error from this line in index.vue
```
onMounted(() => {
  scroll(animate('#bigSlash', {x: 0, y: 100}));
});
```

**Comment by ipatate** [comment]
i think is a problem with target '#bigSlash'. it's probably better to use ref to element for don't loose element.

**Comment by ipatate** [comment]
i have searched a solution but the problem apparently is the Icon component. ref work fine with classic element but not with Icon component.
