### ISSUE TITLE
Add ping to Google when we publish a new episode

### ISSUE THREAD

**Issue by ipatate** [double-slash-podcast/website#57]
- [x] add sitemaps
- [ ] ping google on new episode https://www.google.com/ping?sitemap=FULL_URL_OF_SITEMAP

**Comment by xlanex6** [comment]
We can use Netlify build plugin for that 
After build and deploy 
ping XXX

it should work

Sitemap is already done,  I think 😉

**Comment by ipatate** [comment]
yes, but we need to alert google only when we publish a new episode, not for all deployment :)

**Comment by xlanex6** [comment]
after deploy
 netlify webhook 
ping google sitemap refresh
